// Copyright 2026 TIER IV, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

#include "bagwiz/core/image/compressed_video.hpp"

#include "bagwiz/core/cdr_walker/cdr_reader.hpp"
#include "bagwiz/core/cdr_walker/cdr_writer.hpp"
#include "bagwiz/core/image/stamp_wire.hpp"
#include "bagwiz/core/msg_yaml/msg_definition_resolver.hpp"

#include <cstdint>
#include <exception>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace bagwiz::core::image
{

namespace
{

// foxglove_msgs/msg/CompressedVideo as rosbag2 records it into an MCAP Schema
// record: the ROS 2 .msg from the Foxglove SDK
// (schemas/ros2/CompressedVideo.msg, blob 19041bc) followed by the one
// dependency section, builtin_interfaces/Time, in rosbag2's concatenated
// form. Used when no foxglove_msgs package is installed to resolve the
// definition from; kept byte-for-byte so a bag written here matches one
// written by rosbag2 with the package present.
const char * const kCompressedVideoWireSchema =
  "# foxglove_msgs/msg/CompressedVideo\n"
  "# A single frame of a compressed video bitstream\n"
  "\n"
  "# Generated by https://github.com/foxglove/foxglove-sdk\n"
  "\n"
  "# Timestamp of video frame\n"
  "builtin_interfaces/Time timestamp\n"
  "\n"
  "# Frame of reference for the video.\n"
  "# \n"
  "# The origin of the frame is the optical center of the camera. +x points to the "
  "right in the video, +y points down, and +z points into the plane of the video.\n"
  "string frame_id\n"
  "\n"
  "# Compressed video frame data.\n"
  "# \n"
  "# For packet-based video codecs this data must begin and end on packet boundaries "
  "(no partial packets), and must contain enough video packets to decode exactly one "
  "image (either a keyframe or delta frame). Note: Foxglove does not support video "
  "streams that include B frames because they require lookahead.\n"
  "# \n"
  "# Specifically, the requirements for different `format` values are:\n"
  "# \n"
  "# - `h264`\n"
  "#   - Use Annex B formatted data\n"
  "#   - Each CompressedVideo message should contain enough NAL units to decode "
  "exactly one video frame\n"
  "#   - Each message containing a key frame (IDR) must also include a SPS NAL unit\n"
  "# \n"
  "# - `h265` (HEVC)\n"
  "#   - Use Annex B formatted data\n"
  "#   - Each CompressedVideo message should contain enough NAL units to decode "
  "exactly one video frame\n"
  "#   - Each message containing a key frame (IRAP) must also include relevant "
  "VPS/SPS/PPS NAL units\n"
  "# \n"
  "# - `vp9`\n"
  "#   - Each CompressedVideo message should contain exactly one video frame\n"
  "# \n"
  "# - `av1`\n"
  "#   - Use the \"Low overhead bitstream format\" (section 5.2)\n"
  "#   - Each CompressedVideo message should contain enough OBUs to decode exactly one "
  "video frame\n"
  "#   - Each message containing a key frame must also include a Sequence Header OBU\n"
  "uint8[] data\n"
  "\n"
  "# Video format.\n"
  "# \n"
  "# Supported values: `h264`, `h265`, `vp9`, `av1`.\n"
  "# \n"
  "# Note: compressed video support is subject to hardware limitations and patent "
  "licensing, so not all encodings may be supported on all platforms. See more about "
  "[H.265 support](https://caniuse.com/hevc), [VP9 support](https://caniuse.com/webm), "
  "and [AV1 support](https://caniuse.com/av1).\n"
  "string format\n"
  "================================================================================\n"
  "MSG: builtin_interfaces/Time\n"
  "# This message communicates ROS Time defined here:\n"
  "# https://design.ros2.org/articles/clock_and_time.html\n"
  "\n"
  "# The seconds component, valid over all int32 values.\n"
  "int32 sec\n"
  "\n"
  "# The nanoseconds component, valid in the range [0, 1e9), to be added to the seconds "
  "component. \n"
  "# e.g.\n"
  "# The time -1.7 seconds is represented as {sec: -2, nanosec: 3e8}\n"
  "# The time 1.7 seconds is represented as {sec: 1, nanosec: 7e8}\n"
  "uint32 nanosec\n";

}  // namespace

CompressedVideoResult extract_compressed_video(std::span<const std::byte> payload)
{
  CompressedVideoResult result;
  try {
    cdr_walker::CdrReader reader(payload);

    const std::int32_t stamp_sec = reader.read_i32();       // timestamp.sec
    const std::uint32_t stamp_nanosec = reader.read_u32();  // timestamp.nanosec
    std::string frame_id = reader.read_string();

    const std::uint32_t data_len = reader.read_sequence_length();
    const std::span<const std::byte> data = reader.read_bytes(data_len);

    std::string format = reader.read_string();

    CompressedVideoView view;
    view.timestamp_ns = join_stamp_ns(stamp_sec, stamp_nanosec);
    view.frame_id = std::move(frame_id);
    view.data = data;
    view.format = std::move(format);
    result.video = std::move(view);
  } catch (const std::exception & e) {
    result.video.reset();
    result.error =
      std::string("failed to parse foxglove_msgs/msg/CompressedVideo payload: ") + e.what();
  }
  return result;
}

std::vector<std::byte> serialize_compressed_video(
  std::int64_t timestamp_ns, std::string_view frame_id, std::string_view format,
  std::span<const std::byte> data)
{
  const WireStamp stamp = split_stamp_ns(timestamp_ns);
  cdr_walker::CdrWriter writer;
  writer.write_i32(stamp.sec);
  writer.write_u32(stamp.nanosec);
  writer.write_string(frame_id);
  writer.write_sequence_length(static_cast<std::uint32_t>(data.size()));
  writer.write_bytes(data);
  writer.write_string(format);
  return writer.take();
}

io::TopicInfo make_compressed_video_topic_info(std::string_view topic_name)
{
  io::TopicInfo info;
  info.name.assign(topic_name.begin(), topic_name.end());
  info.type = kCompressedVideoType;
  info.serialization_format = "cdr";
  info.schema_encoding = "ros2msg";
  // Prefer the definition an installed foxglove_msgs ships (the bag then
  // matches the reader's own package); fall back to the embedded copy.
  auto resolved = core::resolve_message_definition(kCompressedVideoType);
  if (!resolved.text.empty()) {
    info.schema_text = std::move(resolved.text);
  } else {
    info.schema_text = kCompressedVideoWireSchema;
  }
  return info;
}

}  // namespace bagwiz::core::image
